### ISSUE TITLE
Drag links to opposite tab

### ISSUE THREAD

**Issue by stutrek** [kura52/sushi-browser#1]
I love the browser, trying to use it as my primary.

I would like to be able to drag a link into the opposite tab to have it open in that tile.

**Comment by kura52** [comment]
Thank you for raising this issue.
I fixed it.  

![fix](https://user-images.githubusercontent.com/16491181/28994897-ae67a1e4-7a14-11e7-8ffc-774fe139ea6b.gif)

**Comment by stutrek** [comment]
🤘 

I'm loving the browser, it's become my default on my big work monitor. Speaking of which, I can't make it the OS browser yet :). When I get some time I want to help contribute.

Are there keyboard shortcuts in the new version?

Changing the tab when you use the scroll wheel throws me off, I don't like it as a feature.

Do you want me to create issues for all the things I find?

**Comment by kura52** [comment]
Thank you for confirmation.

>Are there keyboard shortcuts in the new version?
>Changing the tab when you use the scroll wheel throws me off, I don't like it as a feature.
>Do you want me to create issues for all the things I find?
I summarized what I will do next in [TODO](https://github.com/kura52/sushi-browser#todo).
However, it will be a great help if raising issues.
