### ISSUE TITLE
Page with Basic Auth doesn't show login popup

### ISSUE THREAD

**Issue by DiegoYungh** [kura52/sushi-browser#12]
When you access a page where the server filters access with some kind of HTTP Auth, you normally would be presented with a login dialog.

On this case all I get is the restricted response instead of the login.
I then looked around to find somehow a way to append a BasicAuth hash to the request headers and there is no current way.

Since this is mainly for developers I don't mind injecting header variables, but the login dialog would be nicer, expecially if it remembers the user/password, which is something that usually Chrome and Firefox don't do for this kind of Auth.

**Comment by kura52** [comment]
Thank you for raising this issue.
I Fixed basic auth method in [v0.13.7](https://github.com/kura52/sushi-browser/releases/tag/0.13.7).

**Comment by kura52** [comment]
I close this issue.
