### ISSUE TITLE
Default Browser Selection on Windows

### ISSUE THREAD

**Issue by Koetype** [kura52/sushi-browser#13]
Hello. I noticed on Windows 10 that Sushi cannot be set as the default browser because it is not listed in the registry. Additionally, selecting it as the default by file type, protocol, or app is not possible. These may affect other versions of Windows like 7 and 8.1.

Thank you for your continued work on Sushi Browser, Kura. The multi-panel feature has great applications for work and personal use.

**Comment by kura52** [comment]
Thank you for raising this issue.
It can be set as default browser in my Windows 10 machine by the following procedure.

1. Download and unzip the attached bat file and select "Run as administrator" from the right click menu.
2. Navigate to Settings > Select System > Click Default apps in the left pane > Select "Sushi" on Web browser section.

*If you are using a portable version, please overwrite "C:\Users\\%username%\AppData\Local\sushi\sushi.exe" in the batch file.

[add_default_browser.bat.zip](https://github.com/kura52/sushi-browser/files/1799887/add_default_browser.bat.zip)

**Comment by Koetype** [comment]
The .bat file works well. Thank you for resolving this, Kura.
