### ISSUE TITLE
MHT files

### ISSUE THREAD

**Issue by pfsixtyfive** [kura52/sushi-browser#16]
Hello
many compliments for Sushi browser.
How is possible to save a filein MHT format?
Firefox and Chrome addons for this not play

Thanks

**Comment by kura52** [comment]
Thank you for raising this issue.
I added a function to save to MHTML with v 20.0.

**Comment by pfsixtyfive** [comment]
Thank you for the update.
Now, if the use of RAM and CPU is low.. Sushi browser is perfect.
Thank You
