### ISSUE TITLE
Possibility to activate extensions developper mode (Add local extensions)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#22]
Starting using [AdNauseam](https://github.com/dhowe/AdNauseam) recently, this extension isn't available on the chrome web store for diverse reasons, however, it make me unable to add it to sushi browser. (Or maybe we can, but i don't really found how)

**Comment by kura52** [comment]
Thank you for raising a lot of issues.
I implemeted it in v0.21.1.
