### ISSUE TITLE
French language (Atleast) is completly corrupted.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#23]
![image](https://user-images.githubusercontent.com/13170204/44385648-534ea680-a520-11e8-99b5-9741149c67ad.png)
Was a issue i was aware about for a long time. They're quite a couple of issues with it, that i don't quite understand however they're reasons on it.

- Untranslated strings > Same as chrome _(That's generally acceptable)_
- Incorrect characters > Page d&apos;accueil= Page d**'**accueil _(That's quite common, and definitely need to be fixed to be able to use it correctly)_
- Incorrect translated strings from other language > Aktifkan Perlindungan Tracing (misalnya Google Analytics) _(That the real issue, What's happening here ?)_

I didn't checked with other language as this time of writing, would post an another comment if this sadly affect other languages.

**Comment by kura52** [comment]
Thank you for raising this issues.
I fixed it in v0.21.1.
