### ISSUE TITLE
[Bug] Rick-click menu, "Translate via Google Translation" button is invisible.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#25]
![image](https://user-images.githubusercontent.com/13170204/44416599-9ab25280-a573-11e8-8c4c-12ce76ffd42c.png)
Like showed, The button does still works, but show nothing at all. Done on the default English language.

**Comment by kura52** [comment]
Thank you for raising this issues.
I'm sorry. I could not reproduce this problem.
