### ISSUE TITLE
Does the VPN mode still work ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#26]
By comparing to the VPN mode gif, showed on the Sushi Browser tip, I can only say to myself that it's not working for me. When clicking on the change VPN mode, no external menus with the list of servers appears.
![image](https://sushib.me/tips/img/privacy-vpn.gif)
Personaly, Being on Windows 10 Insider Preview 18219.1000 (rs_prerelease) currently, While this affect it in any way ? _Is they're some logs i can give to help a bit the debugging of this feature ?_

**Comment by kura52** [comment]
Thank you for raising this issues.
I fixed it in v0.21.1.
This bug occurred due to the stricter security constraint of the latest version of muon.
