### ISSUE TITLE
Tabs and tiling settings are lost on restart

### ISSUE THREAD

**Issue by stutrek** [kura52/sushi-browser#3]
When closing and reopening the browser it is helpful to restore the user's previous state.

**Comment by kura52** [comment]
Thank you for raising this issue.
I added that option in [v0.2.0](https://github.com/kura52/sushi-browser/releases/tag/0.2.0).  

![latestclosetab](https://user-images.githubusercontent.com/16491181/29369731-6d93aa5a-82de-11e7-8784-c99bdf47dd83.png)
