### ISSUE TITLE
[Suggestion] When a page is "emitting sounds", Move that page preview, next of the page volume slider.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#34]
![Nq6e3Ot3](https://illegal-download.site/Nq6e3Ot3.gif)
I think you can easily see it, It make both of these elements to overlap each other. It would be nice to put the tab preview of the page, under the volume slider, or the opposite.

**Comment by kura52** [comment]
Thank you for raising this issue.
I fixed it in v0.22.0.
