### ISSUE TITLE
Options are in a surprising order when right clicking on links

### ISSUE THREAD

**Issue by stutrek** [kura52/sushi-browser#4]
When clicking on _links_ other browsers put open in new tab/window above back/forward. Clicking on other spaces works as expected.

Chrome:
![image](https://user-images.githubusercontent.com/339327/29034050-fd9e311e-7b64-11e7-9815-1f842c0856a8.png)

Safari:
![image](https://user-images.githubusercontent.com/339327/29034071-0b707f22-7b65-11e7-98e8-f11c84d634da.png)

Firefox:
![image](https://user-images.githubusercontent.com/339327/29034099-2696dd78-7b65-11e7-97bc-f6501fd302e1.png)

**Comment by kura52** [comment]
Thank you for raising this issue.
I changed the order of the right-click menu in [v0.2.0](https://github.com/kura52/sushi-browser/releases/tag/0.2.0).  

In addition, I added many options.
For example, you can choose whether or not you can change the tab with the mouse wheel.  
Also I added keyboard shortcuts that can be changed.  

![contextmenu](https://user-images.githubusercontent.com/16491181/29369798-96411c94-82de-11e7-8be7-4cc6e52481cd.png)

**Comment by stutrek** [comment]
Thanks!
