### ISSUE TITLE
Transition from Muon to Electron

### ISSUE THREAD

**Issue by kura52** [kura52/sushi-browser#40]
Muon is scheduled to cease development, as in Issue below.  
[Question: what's the future of Muon with the upcoming move to Chromium frontend](https://github.com/brave/muon/issues/554)

Therefore, it is necessary to migrate to Electron, but there is a possibility that functions derived from Muon's own function can not be used.  

We aim to make the transition with compatibility as much as possible.

**Comment by Koetype** [comment]
As per the referenced issue, how are you handling Electron's security concerns? I'm interested to know as Muon was created in part to address that.

I hope the development migration has been going well, and thank you for your work on Sushi Browser, Kura.

**Comment by kura52** [comment]
We released the alpha version of the Electron edition!
https://github.com/kura52/sushi-browser/releases/tag/0.23.a1

**Comment by kura52** [comment]
Close by releasing the official version of the chrome edition.
