### ISSUE TITLE
MacOS Zip and DMG are broken

### ISSUE THREAD

**Issue by stutrek** [kura52/sushi-browser#5]
![image](https://user-images.githubusercontent.com/339327/29370718-425140b0-8274-11e7-92b7-ac9410960b02.png)

![image](https://user-images.githubusercontent.com/339327/29370896-c1f42f4e-8274-11e7-849d-37b0ca115066.png)

**Comment by kura52** [comment]
Sorry, I fixed MacOS zip and dmg.
