### ISSUE TITLE
Remotely control Chrome and make it a pseudo Webview

### ISSUE THREAD

**Issue by kura52** [kura52/sushi-browser#55]
Electron webContents can not use the complete Chrome extension, and has many unstable behaviors. Therefore, change the policy to use Chrome remotely (using Chrome Extension and puppeteer) and use it as a pseudo WebView.
Although this improves stability, there is a high possibility that function constraints will occur.

**Comment by Koetype** [comment]
In using Chrome remotely, do you know if this would be able to get around a limitation that the Muon version of Sushi had where extensions were not able to update automatically?

Please keep up the great work, Kura.

**Comment by kura52** [comment]
I am sorry for the late response.
Chrome Extensions will be updated automatically.

We are currently focusing on the Windows version.
The following is the demo screen and the new architecture.
![demo](https://user-images.githubusercontent.com/16491181/54880450-0c46dc00-4e88-11e9-86c8-6479554465f7.png)
![architecture](https://user-images.githubusercontent.com/16491181/54880457-18329e00-4e88-11e9-9f75-c52ae4bae192.png)

**Comment by kura52** [comment]
We released the beta version of the Chrome edition!  
Google Chrome must be installed in order to use this browser.  
https://github.com/kura52/sushi-browser/releases/tag/0.24.0-beta1

**Comment by kura52** [comment]
We released the official version of the Chrome edition!
https://github.com/kura52/sushi-browser/releases/tag/0.24.0
