### ISSUE TITLE
Preferences not saving on MacOS

### ISSUE THREAD

**Issue by stutrek** [kura52/sushi-browser#6]
Didn't try other platforms

Repo steps:
1. Go to preferencecs
2. change them (I was changing my open previous tabs option)
3. quit (the app will close all windows but not quit)
4. quit again
5. reopen
6. view preferences, they're still the defaults

**Comment by kura52** [comment]
Thank you for raising this issue.  

I successfully saved the settings on my MacBook Air.
It is probably caused by a bug that the background process does not end.  

Would you mind executing the same operation again after executing the following command?  

```
pgrep sushi
kill -9 `pgrep sushi`
```

**Comment by stutrek** [comment]
I couldn't get it to work. I tried killing it from the command line after doing a full double quit, after the first quit, and with no quitting at all. Each time it reset all the settings I changed.

Is there a main process dev tools I could open up to look for errors?

**Comment by stutrek** [comment]
Same issue on my home computer, both 15" Retina MacBook Pros

**Comment by kura52** [comment]
I  reproduced this issue.  
There was a problem with the processing at the quit and I fixed it.  
Would you mind checking this issue with [v0.2.1](https://github.com/kura52/sushi-browser/releases/tag/0.2.1)?

>Is there a main process dev tools I could open up to look for errors?  

Main renderer process devtool can opened by pressing Shift+F8.  

As for the main process, I am Confirming issue by looking at console logs.  
```
cd [Applicatino's Folder]
sushi-browser.app/Contents/MacOS/sushi-browser
```

**Comment by stutrek** [comment]
💯
