### ISSUE TITLE
Warning if Chrome is not installed

### ISSUE THREAD

**Issue by OxeStone** [kura52/sushi-browser#60]
Version 0.24.2 complains that Chrome is not installed and quits running. Any suggestions?

**Comment by Rootyjr** [comment]
I think sushi chrome browser required chrome to be installed. If you don’t have it installed that may be your problem.

**Comment by OxeStone** [comment]
Installed Chrome. When I click on sushi both Chrome and sushi open with a blank workspace and nothing else happens. The buttons in the sushi toolbar are nonresponsive, only the close button works.

**Comment by OxeStone** [comment]
Closing this issue and opening a new one.
