### ISSUE TITLE
Chromium Edition: Chrome Windows Crash After Interacting With Dropdown Menus

### ISSUE THREAD

**Issue by Koetype** [kura52/sushi-browser#62]
For the Chromium edition, Chrome windows crash after interacting with dropdown menus on basically any type of page. I've seen this happen for such menus of Atlassian Jira and Chromium settings pages but not on menus of Sushi's internal pages. The native window seems to not crash, but the browser basically has done so because opening new tabs and windows does not work. The reason may be that Sushi's Chromium processes also have crashed as Windows' task manager has shown.

Chromium Settings' Payment Methods Form Example:
![Chromium Edition - Chromium Settings - Payment Methods](https://user-images.githubusercontent.com/13266313/59313588-9f213680-8c7f-11e9-8c05-9b2abf2c9e25.png)

The following is against a black background for emphasis:
![Chromium Edition - Dropdown Interaction Defect](https://user-images.githubusercontent.com/13266313/59313591-a5171780-8c7f-11e9-9031-dca254de6266.png)

Aside from this, the Chromium edition appears to be a little more stable than the standard, Chrome edition. It has the advantage of not having any of its Chrome windows showing a tab bar after doing certain actions like exiting fullscreen view because the tab bar of course does not exist. I've been fine with this in the standard edition because it is mostly easy to fix and to avoid.

This is an example for anyone who would like to know:
![Standard Edition - Native Window and Chrome Window Desynchronization](https://user-images.githubusercontent.com/13266313/59314220-5a4acf00-8c82-11e9-9a90-d357c02dfb37.PNG)

**Comment by kura52** [comment]
Thank you for raising this issue.
I fixed it in v0.25.3.

**Comment by Koetype** [comment]
Thank you, Kura. This has been good on the various pages with dropdown menus that I've checked.
