### ISSUE TITLE
Suggestion: Allow Sushi's History and Address Bar To Be More Chrome-like

### ISSUE THREAD

**Issue by Koetype** [kura52/sushi-browser#64]
I've thought of some navigation-based suggestions for improvement that would be good particularly for users who more are used to such settings of Chrome or Firefox.

Chrome's history groups links together as long as the (sub-)domains and the paths are the same. There is no differentiation between HTTP, HTTPS, or if the site can be accessed with or without something such as "www." Having this setting option ideally would avoid history entry duplication. Please refer to the following images of Sushi and Chrome's history pages for comparison.
![Sushi History Duplicate Entries](https://user-images.githubusercontent.com/13266313/60174260-ac413800-97de-11e9-8be5-f92ce104e130.png)
![Chrome History Entries](https://user-images.githubusercontent.com/13266313/60174275-b2371900-97de-11e9-9e89-c64407c960b9.png)

I'm not sure if an incognito mode will be integrated fully in the Chrome edition, but in relation to this, two options to compensate a little would be to allow for a user-defined blacklist that specifies which URLs and domains will be recorded and for pausing all history recording in the internal history page. After a confirmation, this blacklist ideally, automatically would delete all prior entries that match any expressions.

The blacklist especially would be useful for redirect entries. Aside from the ones mentioned above, Adobe and Google's various login portals cause these, and in at least Chrome, specific redirects are not recorded in the history by default. Some of the redirects still are recorded because it's based on engineering logic as [this article](https://www.ghacks.net/2018/12/18/google-will-take-action-against-website-history-manipulation/) references. It probably would be difficult to create some sort of default list for Sushi, and if a user-defined list isn't all that possible either, then at least allowing history recording to be paused or for the timing with which Sushi's internal history records entries can be delayed would help to avoid this. For example, a history entry for a URL only would be recorded if a user stayed on its page for five seconds, ten seconds, etc. These can be options so that anyone who prefers the current behavior can continue to use it. There are a few approaches that can be taken with this. 

These points relate to the address bar which will show history entries when applicable. However, there are some cases where users would prefer to not have suggestions of recorded history, like with the mentioned redirect entries.
![Address Bar Autocompletion with Duplicate Entries](https://user-images.githubusercontent.com/13266313/60175366-5d48d200-97e1-11e9-87a6-10de45034b64.png)

The dropdown's list can become long depending on the history suggestions that appear, particularly when it queries entries from redirecting login portals. As for the address bar generally, users may rely on just bookmarks suggestions for example, which is believed to be better for privacy because there would be little to no history data for advertisers or other, third parties to read. Firefox has options to turn off history recording, and both Chrome and Firefox basically can do this through extensions such as [History AutoDelete](https://chrome.google.com/webstore/detail/history-autodelete/bhfakmaiadhflpjloimlagikhodjiefj). These extensions do not entirely work with Sushi's history as they do with that of the Chrome puppet. Still, private browsing or incognito mode are not required to achieve this in Chrome or Firefox. As a side note, there also may be a problem where the search and history autocomplete options in the general settings cannot be set to 0. This should be allowed for those who don't want any sort of suggestions. In regards to the autocomplete options, there of course should be one for bookmarks so that the address bar's dropdown can offer bookmarks suggestions when applicable as other browsers are able to do and allow for the above scenario.
![Autocomplete Options](https://user-images.githubusercontent.com/13266313/60174481-1eb21800-97df-11e9-9171-4fe18ba0cda7.png)

**Comment by kura52** [comment]
Thank you for raising this issue.
I fixed it in v0.25.7, but it is not reflected in the past history.

**Comment by Koetype** [comment]
Thank you, Kura. It has been working for me.

Are there any plans to make it so that the address bar also will return bookmark entries? It's okay otherwise because there are alternatives like the sidebar that can be used to search for and open bookmarks.

**Comment by Koetype** [comment]
Thank you, Kura.

I saw your update about the address bar's bookmark auto-completion feature, and it has been working for me. The additional history and address bar features have been nice to have.

Feel free to reopen this issue if anything else that is related should be addressed.

**Comment by kura52** [comment]
Thank you for confirmation.
