### ISSUE TITLE
Suhi and chromium opens separately

### ISSUE THREAD

**Issue by RedGl0w** [kura52/sushi-browser#69]
When I open the latest release of sushi on xubuntu (with i3-gaps) I get chromium on a side and sushi on the other (chromium doesn't turn totally on and sushi is continually loading).
![image](https://user-images.githubusercontent.com/43498612/67564702-d884ab00-f723-11e9-897b-944bef9e82fe.png)
Thanks

**Comment by RedGl0w** [comment]
Thank you

**Comment by RedGl0w** [comment]
But it seems not to work, I had already installed wmctrl

**Comment by PoorPocketsMcNewHold** [comment]
That why #67 is still opened. Something still cause this issue to happen.

**Comment by RedGl0w** [comment]
Ok watching this !
Thanks
